#[derive(Debug, Clone, PartialEq)]
#[repr(u8)]
pub enum Op {
    PushInt      = 0x01,
    PushIntInline = 0x09,
    PushFloat    = 0x02,
    PushStr      = 0x03,
    PushBool     = 0x04,
    PushNull     = 0x05,
    Pop          = 0x06,
    Dup          = 0x07,
    Swap         = 0x08,

    Load         = 0x10,
    Store        = 0x11,
    LoadLocal    = 0x12,
    StoreLocal   = 0x13,
    LoadGlobal   = 0x14,
    StoreGlobal  = 0x15,
    LoadUpvalue  = 0x16,
    StoreUpvalue = 0x17,

    Add          = 0x20,
    Sub          = 0x21,
    Mul          = 0x22,
    Div          = 0x23,
    Mod          = 0x24,
    Neg          = 0x25,
    Pow          = 0x26,
    Concat       = 0x27,

    Eq           = 0x30,
    Neq          = 0x31,
    Lt           = 0x32,
    Gt           = 0x33,
    LtEq         = 0x34,
    GtEq         = 0x35,
    And          = 0x36,
    Or           = 0x37,
    Not          = 0x38,
    In           = 0x39,

    Jump         = 0x40,
    JumpIf       = 0x41,
    JumpIfNot    = 0x42,
    Call         = 0x43,
    CallNative   = 0x44,
    Return       = 0x45,
    TailCall     = 0x46,
    CallMethod   = 0x47,
    Throw        = 0x48,
    EnterTry     = 0x49,
    LeaveTry     = 0x4A,

    MakeArray    = 0x50,
    MakeTuple    = 0x51,
    MakeStruct   = 0x52,
    ArrayGet     = 0x53,
    ArraySet     = 0x54,
    ArrayLen     = 0x55,
    ArrayPush    = 0x56,
    ArrayPop     = 0x57,
    FieldGet     = 0x58,
    FieldSet     = 0x59,
    MakeLambda   = 0x5A,
    Spread       = 0x5B,
    MakeEnum     = 0x5C,
    OptField     = 0x5D,
    OptCall      = 0x5E,
    Interp       = 0x5F,

    ToInt        = 0x60,
    ToFloat      = 0x61,
    ToStr        = 0x62,
    ToBool       = 0x63,
    TypeOf       = 0x64,
    IsNull       = 0x65,
    NotNull      = 0x66,

    Print        = 0x70,
    PrintLn      = 0x71,
    Input        = 0x72,
    Assert       = 0x73,
    Panic        = 0x74,

    ForIter      = 0x80,
    ForIterEnum  = 0x81,
    IterNext     = 0x82,
    Break        = 0x83,
    Continue     = 0x84,

    MatchStart   = 0x90,
    MatchVal     = 0x91,
    MatchRange   = 0x92,
    MatchWild    = 0x93,
    MatchEnd     = 0x94,

    CacheCheck   = 0xA0,
    CacheStore   = 0xA1,
    TimerStart   = 0xA2,
    TimerEnd     = 0xA3,

    Halt         = 0xFF,
}

impl Op {
    pub fn from_u8(b: u8) -> Option<Op> {
        match b {
            0x01 => Some(Op::PushInt),    0x02 => Some(Op::PushFloat),
            0x03 => Some(Op::PushStr),    0x04 => Some(Op::PushBool),
            0x05 => Some(Op::PushNull),   0x06 => Some(Op::Pop),
            0x07 => Some(Op::Dup),        0x08 => Some(Op::Swap),
            0x10 => Some(Op::Load),       0x11 => Some(Op::Store),
            0x12 => Some(Op::LoadLocal),  0x13 => Some(Op::StoreLocal),
            0x14 => Some(Op::LoadGlobal), 0x15 => Some(Op::StoreGlobal),
            0x16 => Some(Op::LoadUpvalue),0x17 => Some(Op::StoreUpvalue),
            0x20 => Some(Op::Add),        0x21 => Some(Op::Sub),
            0x22 => Some(Op::Mul),        0x23 => Some(Op::Div),
            0x24 => Some(Op::Mod),        0x25 => Some(Op::Neg),
            0x26 => Some(Op::Pow),        0x27 => Some(Op::Concat),
            0x30 => Some(Op::Eq),         0x31 => Some(Op::Neq),
            0x32 => Some(Op::Lt),         0x33 => Some(Op::Gt),
            0x34 => Some(Op::LtEq),       0x35 => Some(Op::GtEq),
            0x36 => Some(Op::And),        0x37 => Some(Op::Or),
            0x38 => Some(Op::Not),        0x39 => Some(Op::In),
            0x40 => Some(Op::Jump),       0x41 => Some(Op::JumpIf),
            0x42 => Some(Op::JumpIfNot),  0x43 => Some(Op::Call),
            0x44 => Some(Op::CallNative), 0x45 => Some(Op::Return),
            0x46 => Some(Op::TailCall),   0x47 => Some(Op::CallMethod),
            0x48 => Some(Op::Throw),      0x49 => Some(Op::EnterTry),
            0x4A => Some(Op::LeaveTry),
            0x50 => Some(Op::MakeArray),  0x51 => Some(Op::MakeTuple),
            0x52 => Some(Op::MakeStruct), 0x53 => Some(Op::ArrayGet),
            0x54 => Some(Op::ArraySet),   0x55 => Some(Op::ArrayLen),
            0x56 => Some(Op::ArrayPush),  0x57 => Some(Op::ArrayPop),
            0x58 => Some(Op::FieldGet),   0x59 => Some(Op::FieldSet),
            0x5A => Some(Op::MakeLambda), 0x5B => Some(Op::Spread),
            0x5C => Some(Op::MakeEnum),   0x5D => Some(Op::OptField),
            0x5E => Some(Op::OptCall),    0x5F => Some(Op::Interp),
            0x60 => Some(Op::ToInt),      0x61 => Some(Op::ToFloat),
            0x62 => Some(Op::ToStr),      0x63 => Some(Op::ToBool),
            0x64 => Some(Op::TypeOf),     0x65 => Some(Op::IsNull),
            0x66 => Some(Op::NotNull),
            0x70 => Some(Op::Print),      0x71 => Some(Op::PrintLn),
            0x72 => Some(Op::Input),      0x73 => Some(Op::Assert),
            0x74 => Some(Op::Panic),
            0x80 => Some(Op::ForIter),    0x81 => Some(Op::ForIterEnum),
            0x82 => Some(Op::IterNext),   0x83 => Some(Op::Break),
            0x84 => Some(Op::Continue),
            0x90 => Some(Op::MatchStart), 0x91 => Some(Op::MatchVal),
            0x92 => Some(Op::MatchRange), 0x93 => Some(Op::MatchWild),
            0x94 => Some(Op::MatchEnd),
            0xA0 => Some(Op::CacheCheck), 0xA1 => Some(Op::CacheStore),
            0xA2 => Some(Op::TimerStart), 0xA3 => Some(Op::TimerEnd),
            0x09 => Some(Op::PushIntInline),
            0xFF => Some(Op::Halt),
            _ => None,
        }
    }
}
