use crate::parser::{Node, MatchPattern, InterpPart};

pub fn to_python(ast: &[Node]) -> String {
    let mut out = String::from("# Generated by tstnt transpiler\n\n");
    for node in ast { out.push_str(&node_py(node, 0)); out.push('\n'); }
    out
}

pub fn to_js(ast: &[Node]) -> String {
    let mut out = String::from("// Generated by tstnt transpiler\n\n");
    for node in ast { out.push_str(&node_js(node, 0)); out.push('\n'); }
    out
}

fn indent(n: usize) -> String { "    ".repeat(n) }

fn node_py(node: &Node, d: usize) -> String {
    let pad = indent(d);
    match node {
        Node::FuncDef { name, params, body, .. } => {
            let ps: Vec<String> = params.iter().map(|(n, _)| n.clone()).collect();
            let mut r = format!("{}def {}({}):\n", pad, name, ps.join(", "));
            if body.is_empty() { r.push_str(&format!("{}    pass\n", pad)); }
            else { for n in body { r.push_str(&node_py(n, d+1)); } }
            r
        }
        Node::Assign { name, value, .. } => format!("{}{} = {}\n", pad, name, expr_py(value)),
        Node::Return(v) => format!("{}return {}\n", pad, expr_py(v)),
        Node::If { cond, body, else_body } => {
            let mut r = format!("{}if {}:\n", pad, expr_py(cond));
            for n in body { r.push_str(&node_py(n, d+1)); }
            if let Some(eb) = else_body { r.push_str(&format!("{}else:\n", pad)); for n in eb { r.push_str(&node_py(n, d+1)); } }
            r
        }
        Node::While { cond, body } => {
            let mut r = format!("{}while {}:\n", pad, expr_py(cond));
            for n in body { r.push_str(&node_py(n, d+1)); }
            r
        }
        Node::Loop { var, start, end, body } => {
            let mut r = format!("{}for {} in range({}, {}):\n", pad, var, expr_py(start), expr_py(end));
            for n in body { r.push_str(&node_py(n, d+1)); }
            r
        }
        Node::LoopIn { var, iter, body } => {
            let mut r = format!("{}for {} in {}:\n", pad, var, expr_py(iter));
            for n in body { r.push_str(&node_py(n, d+1)); }
            r
        }
        Node::FuncCall { name, args } => {
            let astr: Vec<String> = args.iter().map(|a| expr_py(a)).collect();
            let pyname = match name.as_str() { "print" => "print", "len" => "len", "str" => "str", "int" => "int", "float" => "float", _ => name };
            format!("{}{}({})\n", pad, pyname, astr.join(", "))
        }
        Node::Break => format!("{}break\n", pad),
        Node::Continue => format!("{}continue\n", pad),
        Node::Throw(v) => format!("{}raise Exception({})\n", pad, expr_py(v)),
        Node::Try { body, catch_var, catch_body } => {
            let mut r = format!("{}try:\n", pad);
            for n in body { r.push_str(&node_py(n, d+1)); }
            r.push_str(&format!("{}except Exception as {}:\n", pad, catch_var));
            for n in catch_body { r.push_str(&node_py(n, d+1)); }
            r
        }
        Node::StructDef { name, fields } => {
            let mut r = format!("{}class {}:\n{}    def __init__(self", pad, name, pad);
            for (f, _) in fields { r.push_str(&format!(", {}", f)); }
            r.push_str("):\n");
            for (f, _) in fields { r.push_str(&format!("{}        self.{} = {}\n", pad, f, f)); }
            r
        }
        _ => format!("{}{}\n", pad, expr_py(node))
    }
}

fn expr_py(node: &Node) -> String {
    match node {
        Node::Number(n) => if n.fract() == 0.0 { format!("{}", *n as i64) } else { n.to_string() }
        Node::Str(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Node::Bool(b) => if *b { "True".into() } else { "False".into() }
        Node::Null => "None".into(),
        Node::Ident(name) => name.clone(),
        Node::BinOp(l, op, r) => {
            let op = match op.as_str() { "&&" => "and", "||" => "or", "!=" => "!=", _ => op };
            format!("({} {} {})", expr_py(l), op, expr_py(r))
        }
        Node::Unary(op, v) => { let op = if op == "!" { "not " } else { op }; format!("({}{})", op, expr_py(v)) }
        Node::FuncCall { name, args } => { let astr: Vec<String> = args.iter().map(|a| expr_py(a)).collect(); format!("{}({})", name, astr.join(", ")) }
        Node::Array(els) => { let es: Vec<String> = els.iter().map(|e| expr_py(e)).collect(); format!("[{}]", es.join(", ")) }
        Node::Ternary(c, t, e) => format!("({} if {} else {})", expr_py(t), expr_py(c), expr_py(e)),
        Node::FieldAccess { obj, field } => format!("{}.{}", expr_py(obj), field),
        Node::Index { obj, idx } => format!("{}[{}]", expr_py(obj), expr_py(idx)),
        Node::Lambda { params, body } => format!("lambda {}: {}", params.join(", "), expr_py(body)),
        Node::Interp(parts) => {
            let mut r = String::from("f\"");
            for p in parts { match p { InterpPart::Literal(s) => r.push_str(s), InterpPart::Expr(e) => { r.push('{'); r.push_str(&expr_py(e)); r.push('}'); } } }
            r.push('"'); r
        }
        _ => "_".into()
    }
}

fn node_js(node: &Node, d: usize) -> String {
    let pad = indent(d);
    match node {
        Node::FuncDef { name, params, body, is_async, .. } => {
            let ps: Vec<String> = params.iter().map(|(n, _)| n.clone()).collect();
            let asyn = if *is_async { "async " } else { "" };
            let mut r = format!("{}{}function {}({}) {{\n", pad, asyn, name, ps.join(", "));
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad)); r
        }
        Node::Assign { name, value, mutable, .. } => {
            let kw = if *mutable { "let" } else { "const" };
            format!("{}{} {} = {};\n", pad, kw, name, expr_js(value))
        }
        Node::Return(v) => format!("{}return {};\n", pad, expr_js(v)),
        Node::If { cond, body, else_body } => {
            let mut r = format!("{}if ({}) {{\n", pad, expr_js(cond));
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad));
            if let Some(eb) = else_body { r.push_str(&format!("{}else {{\n", pad)); for n in eb { r.push_str(&node_js(n, d+1)); } r.push_str(&format!("{}}}\n", pad)); }
            r
        }
        Node::While { cond, body } => {
            let mut r = format!("{}while ({}) {{\n", pad, expr_js(cond));
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad)); r
        }
        Node::Loop { var, start, end, body } => {
            let mut r = format!("{}for (let {} = {}; {} < {}; {}++) {{\n", pad, var, expr_js(start), var, expr_js(end), var);
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad)); r
        }
        Node::LoopIn { var, iter, body } => {
            let mut r = format!("{}for (const {} of {}) {{\n", pad, var, expr_js(iter));
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad)); r
        }
        Node::FuncCall { name, args } => {
            let astr: Vec<String> = args.iter().map(|a| expr_js(a)).collect();
            let jsname = match name.as_str() { "print" => "console.log", "len" => "// len", _ => name };
            format!("{}{}({});\n", pad, jsname, astr.join(", "))
        }
        Node::Break => format!("{}break;\n", pad),
        Node::Continue => format!("{}continue;\n", pad),
        Node::Throw(v) => format!("{}throw new Error({});\n", pad, expr_js(v)),
        Node::Try { body, catch_var, catch_body } => {
            let mut r = format!("{}try {{\n", pad);
            for n in body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}} catch ({}) {{\n", pad, catch_var));
            for n in catch_body { r.push_str(&node_js(n, d+1)); }
            r.push_str(&format!("{}}}\n", pad)); r
        }
        Node::StructDef { name, fields } => {
            let mut r = format!("{}class {} {{\n{}    constructor(", pad, name, pad);
            let fs: Vec<String> = fields.iter().map(|(f, _)| f.clone()).collect();
            r.push_str(&fs.join(", ")); r.push_str(") {\n");
            for (f, _) in fields { r.push_str(&format!("{}        this.{} = {};\n", pad, f, f)); }
            r.push_str(&format!("{}    }}\n{}}}\n", pad, pad)); r
        }
        _ => format!("{}{}\n", pad, expr_js(node))
    }
}

fn expr_js(node: &Node) -> String {
    match node {
        Node::Number(n) => if n.fract() == 0.0 { format!("{}", *n as i64) } else { n.to_string() }
        Node::Str(s) => format!("`{}`", s),
        Node::Bool(b) => b.to_string(),
        Node::Null => "null".into(),
        Node::Ident(name) => name.clone(),
        Node::BinOp(l, op, r) => { let op = match op.as_str() { "&&" => "&&", "||" => "||", _ => op }; format!("({} {} {})", expr_js(l), op, expr_js(r)) }
        Node::Unary(op, v) => { let op = if op == "!" { "!" } else { op }; format!("({}{})", op, expr_js(v)) }
        Node::FuncCall { name, args } => { let astr: Vec<String> = args.iter().map(|a| expr_js(a)).collect(); let n = if name == "print" { "console.log" } else { name }; format!("{}({})", n, astr.join(", ")) }
        Node::Array(els) => { let es: Vec<String> = els.iter().map(|e| expr_js(e)).collect(); format!("[{}]", es.join(", ")) }
        Node::Ternary(c, t, e) => format!("({} ? {} : {})", expr_js(c), expr_js(t), expr_js(e)),
        Node::FieldAccess { obj, field } => format!("{}.{}", expr_js(obj), field),
        Node::OptionalAccess { obj, field } => format!("{}?.{}", expr_js(obj), field),
        Node::Index { obj, idx } => format!("{}[{}]", expr_js(obj), expr_js(idx)),
        Node::Lambda { params, body } => format!("({}) => {}", params.join(", "), expr_js(body)),
        Node::Interp(parts) => {
            let mut r = String::from("`");
            for p in parts { match p { InterpPart::Literal(s) => r.push_str(s), InterpPart::Expr(e) => { r.push_str("${"); r.push_str(&expr_js(e)); r.push('}'); } } }
            r.push('`'); r
        }
        _ => "undefined".into()
    }
}
